"""new-6

Revision ID: 470fe629068a
Revises: 9cb0a6a9d527
Create Date: 2026-04-05 13:35:12.245204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '470fe629068a'
down_revision: Union[str, Sequence[str], None] = '9cb0a6a9d527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('persons', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('persons', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_persons_department'), 'persons', ['department'], unique=False)
    op.alter_column('slots', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('slots', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_persons_department'), table_name='persons')
    op.alter_column('persons', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('persons', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('groups', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
