"""add_columns_config_and_extra_data

Revision ID: 6132af53faf0
Revises: b15f171533d0
Create Date: 2026-04-02 14:42:38.587228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6132af53faf0'
down_revision: Union[str, Sequence[str], None] = 'b15f171533d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('columns_config', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_persons_full_name'), table_name='persons')
    op.create_index(op.f('ix_persons_full_name'), 'persons', ['full_name'], unique=True)
    op.add_column('slots', sa.Column('extra_data', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slots', 'extra_data')
    op.drop_index(op.f('ix_persons_full_name'), table_name='persons')
    op.create_index(op.f('ix_persons_full_name'), 'persons', ['full_name'], unique=False)
    op.drop_column('events', 'columns_config')
    # ### end Alembic commands ###
