"""make_positions_global

Revision ID: 79740d2ea749
Revises: d4093fe1f5d2
Create Date: 2026-04-03 05:30:59.919868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79740d2ea749'
down_revision: Union[str, Sequence[str], None] = 'd4093fe1f5d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('department', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'positions', ['name'])
    op.drop_constraint(op.f('positions_event_id_fkey'), 'positions', type_='foreignkey')
    op.drop_column('positions', 'event_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('positions_event_id_fkey'), 'positions', 'events', ['event_id'], ['id'])
    op.drop_constraint(None, 'positions', type_='unique')
    op.drop_column('persons', 'department')
    # ### end Alembic commands ###
