"""Add Position model and link to Slot

Revision ID: 860cf646432c
Revises: c3d188472407
Create Date: 2026-03-29 15:19:04.333855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '860cf646432c'
down_revision: Union[str, Sequence[str], None] = 'c3d188472407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_id'), 'positions', ['id'], unique=False)
    op.add_column('slots', sa.Column('position_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'slots', 'positions', ['position_id'], ['id'])
    op.drop_column('slots', 'position')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slots', sa.Column('position', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'slots', type_='foreignkey')
    op.drop_column('slots', 'position_id')
    op.drop_index(op.f('ix_positions_id'), table_name='positions')
    op.drop_table('positions')
    # ### end Alembic commands ###
