"""new-3

Revision ID: e87de53f62c3
Revises: 87d3015553ef
Create Date: 2026-04-04 10:16:01.254261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e87de53f62c3'
down_revision: Union[str, Sequence[str], None] = '87d3015553ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('duty_schedules', sa.Column('owner', sa.String(), nullable=True))
    op.create_index(op.f('ix_duty_schedules_owner'), 'duty_schedules', ['owner'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_duty_schedules_owner'), table_name='duty_schedules')
    op.drop_column('duty_schedules', 'owner')
    # ### end Alembic commands ###
